#!/usr/bin/env python3
"""Generate a full newsletter with Obsidian links for browser testing"""

import os
import sys
from datetime import datetime

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from src.news.generator import NewsGenerator
from src.database import init_db
from src.newsletter.builder import build_newsletter_html

def main():
    # Initialize database
    print("Initializing database...")
    init_db()

    print("\nGenerating newsletter with Obsidian links...")
    generator = NewsGenerator(
        provider_name='openrouter',
        api_key=os.getenv('OPENROUTER_API_KEY'),
        model='anthropic/claude-sonnet-4'
    )

    # Generate full digest (higher max_tokens for Obsidian links)
    run_id = generator.generate_news_digest_from_sources(
        max_tokens=12000,  # Increased for Obsidian URI content
        language='nl',
        max_items_per_source=3
    )

    print(f"\n✓ Newsletter generated (run #{run_id})")

    # Build HTML newsletter with Obsidian links
    print("\nBuilding HTML with Obsidian links...")
    newsletter_body = build_newsletter_html(run_id)

    if not newsletter_body:
        print("ERROR: Failed to build HTML newsletter")
        return

    # Wrap in email template
    today = datetime.now().strftime("%Y-%m-%d")
    subject = f"AI News Digest - {today} [NL] - TEST"

    # Build complete HTML with template
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body {{
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Microsoft YaHei', Helvetica, Arial, sans-serif;
                line-height: 1.8;
                color: #24292e;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f6f8fa;
            }}
            .container {{
                background-color: #ffffff;
                border-radius: 8px;
                padding: 40px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            }}
            .title {{
                color: #0366d6;
                font-size: 32px;
                font-weight: 700;
                margin-bottom: 20px;
                padding-bottom: 15px;
                border-bottom: 4px solid #0366d6;
                text-align: center;
            }}
            .content {{
                margin-top: 30px;
            }}
            .content h3 {{
                color: #24292e;
                font-size: 18px;
                font-weight: 600;
                margin-top: 28px;
                margin-bottom: 15px;
                padding-left: 12px;
                border-left: 4px solid #0366d6;
            }}
            .content p {{
                margin: 15px 0;
                line-height: 1.8;
                color: #24292e;
            }}
            .content ul, .content ol {{
                margin: 15px 0;
                padding-left: 30px;
            }}
            .content li {{
                margin: 10px 0;
                line-height: 1.8;
            }}
            .content strong {{
                font-weight: 600;
                color: #0366d6;
            }}
            .content hr {{
                border: none;
                border-top: 2px solid #e1e4e8;
                margin: 30px 0;
            }}
            .content a {{
                color: #0366d6;
                text-decoration: none;
                border-bottom: 1px solid transparent;
                transition: border-bottom 0.2s;
            }}
            .content a:hover {{
                border-bottom: 1px solid #0366d6;
            }}
            .footer {{
                margin-top: 50px;
                padding-top: 25px;
                border-top: 2px solid #e1e4e8;
                text-align: center;
                font-size: 14px;
                color: #586069;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="title">{subject}</div>
            <div class="content">
                {newsletter_body}
            </div>
        </div>
        <div class="footer">
            <p>This email was automatically generated by AI News Bot</p>
        </div>
    </body>
    </html>
    """

    # Save HTML to file
    output_file = f'test_newsletter_{datetime.now().strftime("%Y%m%d_%H%M")}.html'
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(html_content)

    print(f"✓ HTML newsletter saved to: {output_file}")

    # Count Obsidian links
    obs_count = html_content.count('[Obs]')
    print(f"✓ Found {obs_count} Obsidian links in newsletter")

    # Open in browser
    import webbrowser
    file_path = os.path.abspath(output_file)
    print(f"\nOpening in browser: {file_path}")
    webbrowser.open(f'file://{file_path}')

if __name__ == '__main__':
    main()
